import {useMemo,useState} from 'react';
import {useNavigate,useParams} from 'react-router-dom';
import {allProducts,services} from '../data/catalog';
import Icon from '../components/ui/Icon';
import {useCart} from '../context/CartContext';

const categoryForSlug={shopping:'shopping',food:'food',medicine:'medicine',hotel:'hotel',flight:'travel'};
const forms={recharge:{label:'Mobile number',placeholder:'10-digit mobile number'},bills:{label:'Account number',placeholder:'Consumer / account number'},money:{label:'Recipient UPI ID',placeholder:'name@bank'},movie:{label:'City',placeholder:'Enter your city'},doctor:{label:'Specialty',placeholder:'Choose specialty'},labs:{label:'Test package',placeholder:'Choose a test'},donate:{label:'Donation amount',placeholder:'₹ amount'},nearby:{label:'Search area',placeholder:'Area or landmark'},insurance:{label:'Insurance type',placeholder:'Health, life, vehicle or travel'},gold:{label:'Investment amount',placeholder:'₹ amount'},gifts:{label:'Recipient',placeholder:'Recipient name'},education:{label:'Learning goal',placeholder:'Course or certification'},government:{label:'Service',placeholder:'Choose a government service'}};

export default function ServicePage(){
 const {slug='more'}=useParams(); const nav=useNavigate(); const service=services[slug]||services.more; const {addToCart}=useCart();
 const [query,setQuery]=useState(''); const [sort,setSort]=useState('popular'); const [notice,setNotice]=useState(''); const [form,setForm]=useState('');
 const category=categoryForSlug[slug];
 const list=useMemo(()=>allProducts.filter(p=>category?p.category===category:false).filter(p=>!query||`${p.name} ${p.tag} ${p.seller}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='price'?a.price-b.price:sort==='rating'?b.rating-a.rating:0),[category,query,sort]);
 const hasProducts=Boolean(category)&&list.length>0;
 const action=()=>{if(!form.trim()&&forms[slug]){setNotice(`Please enter ${forms[slug].label.toLowerCase()}.`);return} setNotice(slug==='movie'?'Showtimes found. Select a show to continue.':`${service.title} request started successfully.`)};
 return <div className="servicePage">
  <button className="backLink" onClick={()=>nav(-1)}><Icon name="arrow" size={15}/> Back</button>
  <section className="serviceHero"><div className="serviceHeroCopy"><span className="eyebrow">{service.eyebrow}</span><h1>{service.title}</h1><p>{service.subtitle}</p><div className="serviceFeatureList">{service.features.map(f=><span key={f}><Icon name="check" size={14}/>{f}</span>)}</div></div><img src={service.image} alt={service.title}/></section>
  {hasProducts&&<section className="section serviceCatalog"><div className="sectionHead"><div><span className="eyebrow">{slug==='food'?'RESTAURANTS & FOOD':'CATALOG'}</span><h2>{slug==='food'?'Order food, not gadgets':'Browse '+service.title}</h2><p>{list.length} relevant items available</p></div><div className="catalogTools"><div className="miniSearch"><Icon name="search" size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${slug==='food'?'food':'this section'}`}/></div><select value={sort} onChange={e=>setSort(e.target.value)}><option value="popular">Recommended</option><option value="rating">Top rated</option><option value="price">Lowest price</option></select></div></div><div className="catalogGrid">{list.map(p=><article className="catalogCard" key={p.id} onClick={()=>nav(`/product/${p.id}`)}><div className="catalogImage"><img src={p.image} alt={p.name}/><span>{p.tag}</span></div><div className="catalogInfo"><small>{p.seller}</small><h3>{p.name}</h3><div className="catalogMeta"><strong>₹{p.price.toLocaleString('en-IN')}</strong><del>₹{p.oldPrice.toLocaleString('en-IN')}</del><span>★ {p.rating}</span></div><button onClick={e=>{e.stopPropagation();addToCart(p);setNotice(`${p.name} added to cart.`)}}>Add to cart <Icon name="plus" size={15}/></button></div></article>)}</div></section>}
  {!hasProducts&&<section className="section actionSection"><div className="sectionHead"><div><span className="eyebrow">{forms[slug]?'SECURE REQUEST':'SERVICE ACTION'}</span><h2>{forms[slug]?`Start ${service.title}`:'Choose what you want to do'}</h2><p>This action stays inside the selected service instead of sending you back to Home.</p></div></div><div className="actionGrid">{service.features.map((f,i)=><button className="actionTile" key={f} onClick={()=>setForm(f)}><span className="actionNumber">0{i+1}</span><div><b>{f}</b><small>Open {f.toLowerCase()} options</small></div><Icon name="arrow" size={17}/></button>)}</div>{(forms[slug]||form)&&<div className="requestPanel"><div className="requestIcon"><Icon name="check" size={22}/></div><div className="requestFields">{forms[slug]?<><label>{forms[slug].label}<input value={form} onChange={e=>setForm(e.target.value)} placeholder={forms[slug].placeholder}/></label><button className="primary" onClick={action}>Continue <Icon name="arrow" size={16}/></button></>:<><h3>{form}</h3><p>Selected successfully. Continue to the next step for this service.</p><button className="primary" onClick={action}>Continue <Icon name="arrow" size={16}/></button></>}</div></div>}{notice&&<div className="inlineNotice"><Icon name="check" size={17}/><span>{notice}</span></div>}</section>}
 </div>
}
